### ISSUE TITLE
Remove the initial pop upIalert) message while loading the page

### ISSUE THREAD

**Issue by pantbibek21** [souvikrajsingh/StudentHelp#16]
@souvikrajsingh sir, we have this alert message while we are loading the page. I guess this is ruining the user experience as they have to respond to alerts else no interaction is possible. Also, the fact that the more distinct data there will be, the more times the pop-up will be generated as it is inside the loop. So I have created this issue to remove it to have a better user experience. If you feel okay, let me have a chance to remove this. This won't affect any other functionality : )
You can assign me to solve this issue or if you don't think it's a good idea, you can simply close the issue.

**Comment by souvikrajsingh** [comment]
Sure bibek create a issue and I'll assign it to you 👌

**Comment by souvikrajsingh** [comment]
sure assigning this issue to you right now ! 👌🏽

**Comment by souvikrajsingh** [comment]
hey @pantbibek21 Like you asked the repo is hosted at https://souvikrajsingh.github.io/StudentHelp/ please check it out

Thanks for the idea 💡

**Comment by pantbibek21** [comment]
Yes, it looks much better now and it will be easier to for other to see and contribute : )
Thanks.
