### ISSUE TITLE
want to add a open source opportunity which is not in list

### ISSUE THREAD

**Issue by krishna120801** [souvikrajsingh/StudentHelp#19]

**Comment by souvikrajsingh** [comment]
@krishna120801 Kindly write a description about what opportunity you want to add. Good Ideas are always welcomed!🙏🏽

**Comment by krishna120801** [comment]
@souvikrajsingh ! I want to add about github campus expert program.

**Comment by souvikrajsingh** [comment]
> @souvikrajsingh ! I want to add about github campus expert program.

Sure @krishna120801 github campus expert program opens twice a year once in Feb and again in August please add github campus expert in August 

February one is already added by @Suga7772

**Comment by krishna120801** [comment]
hi! @souvikrajsingh ! issue is resolved, please merge my PR and close this issue!

**Comment by souvikrajsingh** [comment]
> hi! @souvikrajsingh ! issue is resolved, please merge my PR and close this issue!

Thanks for contributing !
