### ISSUE TITLE
Make changes to CONTRIBUTING.md file if needed

### ISSUE THREAD

**Issue by souvikrajsingh** [souvikrajsingh/StudentHelp#3]
make the CONTRIBUTING.md file more easy to understand and readable if you can in some way, be it by adding emojis pictures or videos to help the folks doing it for the first time

**Comment by pantbibek21** [comment]
Hello sir, I would love to work on this issue as well : ) Please, assign it to me, so I could start the work right away.

**Comment by amanaggarwal06** [comment]
Hey, I wanted to do this.
Can you please assign it to me?

**Comment by souvikrajsingh** [comment]
> Hey, I wanted to do this. Can you please assign it to me?

@amanaggarwal06 are you working on this issue??

**Comment by amanycodes** [comment]
Hey, I would like to work on this issue. Can you please assign me this issue?

**Comment by souvikrajsingh** [comment]
Sure ! Get started !
