### ISSUE TITLE
Fix the background in  CSS 

### ISSUE THREAD

**Issue by souvikrajsingh** [souvikrajsingh/StudentHelp#36]
The white portion should normally be appearing over the whole section. Make changes to repo to fix this isssue.

You can check the error here 👉🏽 [Error Image ](https://drive.google.com/file/d/1kyPuNrErS4bvjIHgFKqNVVNSkZY__UuZ/view?usp=sharingl)

**Comment by Gowrishankar04** [comment]
Hi @souvikrajsingh ,

Can you please assign this to me?

Thanks

**Comment by souvikrajsingh** [comment]
Go ahead @Gowrishankar04 ! good luck! 👌🏽

**Comment by souvikrajsingh** [comment]
@Gowrishankar04 This issue has already been resolved. Thanks for contributing!

if you make the table look any better, please create a issue i would love to assign it to you! Cheers mate
