### ISSUE TITLE
center the  table to the center for better user experience

### ISSUE THREAD

**Issue by pantbibek21** [souvikrajsingh/StudentHelp#4]
Sir, it would be more better if we could align the table to the center. That extra space looks awkward, isn't it? So could you assign this issue to me, I would love to solve this.

**Comment by souvikrajsingh** [comment]
right, i have assinged you this issue as well !

**Comment by Manishgupta200** [comment]
I would like to work on this issue. Assign it to me

**Comment by pantbibek21** [comment]
@souvikrajsingh sir, you can close this and all other solved issues. This can create confusion for others if still kept open even after having a PR being merged, right?
