### ISSUE TITLE
Add functionality to ONLY the Opens Option 

### ISSUE THREAD

**Issue by souvikrajsingh** [souvikrajsingh/StudentHelp#44]
the opens option on the top cannnot filter the months, add some functionality only to the Opens option!

Check how it looks when trying to filter out the months 👉🏽[Heading Error](https://drive.google.com/file/d/1bqAnneBbmx2iQfa8zFlvouh8pSFC_RCB/view?usp=sharing)

**Comment by Ishikasaraf20** [comment]
hey @souvikrajsingh i can work on it can you assign this to me

**Comment by souvikrajsingh** [comment]
Sure @Ishikasaraf20 go ahead!

**Comment by souvikrajsingh** [comment]
@Ishikasaraf20 any updates ?

**Comment by souvikrajsingh** [comment]
@Ishikasaraf20 Any updates for the issue Ishika?! 

I need to close this issue otherwise
