### ISSUE TITLE
Add Hacker Rank to the list in the index file

### ISSUE THREAD

**Issue by Kirkkm** [souvikrajsingh/StudentHelp#46]
Hacker Rank is a great site to practice coding on many different languages & a site that employers use for their technical interviews as well.

**Comment by Kirkkm** [comment]
Can you assign this to me with the hactoberfest tag? I have it ready to be committed and merged.

**Comment by souvikrajsingh** [comment]
@Kirkkm Thanks for the interset but here we are gathering all sorts fo opportunites be it a hackathon, intership, student program and mentorship programs.

I would love to have you contributing to this repo!

Thanks

**Comment by Kirkkm** [comment]
Sure, what else needs to be done in the Repo?

**Comment by souvikrajsingh** [comment]
> Sure, what else needs to be done in the Repo?

the website looks basic for now! can you work on how it looks ? Maybe add some funtionality features or different gradient or make it look a little better 

Please @Kirkkm share if you  have any ideas ! Cheers🙏🏽
