### ISSUE TITLE
Want to add a web3 bootcamp that runs twice a year

### ISSUE THREAD

**Issue by olybeke** [souvikrajsingh/StudentHelp#49]
- A web3 bootcamp that runs twice a year.
- focuses on both web2 and also web3 learning development.

**Comment by olybeke** [comment]
can you please look at this and assign it to me , so I could add it to the list? Thanks.

**Comment by souvikrajsingh** [comment]
Is it like a Free bootcamp? @olybeke

**Comment by olybeke** [comment]
yes, it is @souvikrajsingh

**Comment by souvikrajsingh** [comment]
@olybeke i would love to have you contribute to this repo but bootcamps are not counted ! you can write about a student program, hackathons , internships or a reasearch program! i am trying to avoid bootcamps!

had some bootcamps merged in the repo, will remove it ASAP!

**Comment by olybeke** [comment]
ohh okay. would try to look for other opportunities that you mentioned or look into other issues, I'm still open to contributing to this project. Thanks

**Comment by olybeke** [comment]
should I delete this issue?

**Comment by souvikrajsingh** [comment]
yes ! would you like to work on the appearence of the table ? maybe make it more appealing to the eye.

I think the blue is too much for the eyes haha!

**Comment by olybeke** [comment]
yeah, i figured out the color wasn't really appealing and a few more changes would do.
I will make a pr when I'm done with the changes.
