### ISSUE TITLE
Technical Blogs Website

### ISSUE THREAD

**Issue by geetika001** [souvikrajsingh/StudentHelp#7]
Hey @souvikrajsingh since you are working on providing information about all the programs to students,it would be a great idea to make a technical blogs website.
some screenshots to show how it will look:
![image](https://user-images.githubusercontent.com/98944568/196614017-9d874c84-f828-49a3-b1f5-679085948403.png)
![image](https://user-images.githubusercontent.com/98944568/196614068-0bf7cf33-46ff-4b07-b953-c172b22d0142.png)
![image](https://user-images.githubusercontent.com/98944568/196614036-1a011264-a922-4455-8e6d-77039c5f7256.png)
![Uploading image.png…]()

Please allow me to work on it and please consider it for Hacktoberfest.We can add information in this kind of website as well.It will have animations.

**Comment by souvikrajsingh** [comment]
great idea @geetika001, i have assigned you the issue you can get stared ! ⚡

**Comment by souvikrajsingh** [comment]
@geetika001 it would be great if the topics are like you sent and the table itself on the top where the students can see and filter out what they are looking for.

![image](https://user-images.githubusercontent.com/98944568/196614017-9d874c84-f828-49a3-b1f5-679085948403.png)

great idea geetika. Get started ⚡

**Comment by geetika001** [comment]
@souvikrajsingh please review and read the conversation of PR #8 .Hoping to get it merged.
